# -*- coding: utf-8 -*-
"""E-Commerce

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lneo0qJSAAOxnLsJTo3WCbut_oH9hWcH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set random seed for reproducibility
np.random.seed(42)

# --- 1. Generate a synthetic dataset ---
N_ROWS = 500
categories = ['Electronics', 'Clothing', 'Groceries', 'Books', 'Home Goods']
payment_methods = ['Credit Card', 'Debit Card', 'PayPal', 'Cash']

# Generate data
purchase_amounts = np.random.normal(loc=50, scale=20, size=N_ROWS).clip(min=0) # Ensure no negative amounts
product_categories = np.random.choice(categories, size=N_ROWS)
transaction_dates = pd.to_datetime('2025-01-01') + pd.to_timedelta(np.random.randint(0, 365, size=N_ROWS), unit='D')
payment_methods_data = np.random.choice(payment_methods, size=N_ROWS)
transaction_ids = [f'T{i+1000}' for i in range(N_ROWS)]
customer_ids = [f'C{np.random.randint(1, 101)}' for _ in range(N_ROWS)] # 100 unique customers

# Create DataFrame
df = pd.DataFrame({
    'PurchaseAmount': purchase_amounts,
    'ProductCategory': product_categories,
    'TransactionDate': transaction_dates,
    'PaymentMethod': payment_methods_data,
    'TransactionID': transaction_ids,
    'CustomerID': customer_ids
})


# --- 2. Load and inspect the data ---
print("--- Data Inspection ---")
print(df.head())
print("\nData Types and Missing Values:")
print(df.info())
# No missing values were introduced in this specific generation method.

# --- 3. Calculate descriptive statistics ---
print("\n--- Descriptive Statistics ---")
# Overall statistics
overall_stats = df['PurchaseAmount'].describe()
print("\nOverall PurchaseAmount Statistics:")
print(overall_stats[['mean', '50%', 'std']]) # mean, median (50%), std

# Grouped statistics
grouped_stats = df.groupby('ProductCategory')['PurchaseAmount'].agg(['mean', 'median', 'std'])
print("\nPurchaseAmount Statistics Grouped by Category:")
print(grouped_stats)

# --- 4. Create two distinct visualizations ---
sns.set_style("whitegrid")

# Visualization 1: Distribution of PurchaseAmount (Histogram)
plt.figure(figsize=(10, 6))
sns.histplot(df['PurchaseAmount'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Purchase Amounts')
plt.xlabel('Purchase Amount ($)')
plt.ylabel('Frequency')
plt.show()

# Visualization 2: Count of transactions per ProductCategory (Bar Chart)
plt.figure(figsize=(10, 6))
sns.countplot(y='ProductCategory', data=df, order=df['ProductCategory'].value_counts().index, palette='viridis')
plt.title('Transaction Count per Product Category')
plt.xlabel('Number of Transactions')
plt.ylabel('Product Category')
plt.show()

# --- 5. Write a brief summary ---
print("\n--- Summary Interpretation ---")
# The statistics show that the average purchase amount is around $50.
# The histogram reveals a distribution that is relatively normal but slightly skewed right, indicating most purchases are lower value, with fewer high-value transactions.
# The bar chart shows that transaction counts are relatively evenly distributed across the 'Electronics', 'Clothing', and 'Groceries' categories, while 'Books' and 'Home Goods' have fewer transactions.